// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillCraft.Api.Infrastructure;

#nullable disable

namespace SkillCraft.Api.PostgreSQL.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260720162624_CreateCasteTable")]
    partial class CreateCasteTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillCraft.Api.Core.Castes.Caste", b =>
                {
                    b.Property<int>("CasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CasteId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureHtmlContent")
                        .HasColumnType("text");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Skill")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("WealthRoll")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("CasteId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "FeatureName");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Skill");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Castes", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Customizations.Customization", b =>
                {
                    b.Property<int>("CustomizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomizationId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomizationId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Kind");

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Customizations", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Languages.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ScriptId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypicalSpeakers")
                        .HasColumnType("text");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguageId");

                    b.HasIndex("ScriptId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "ScriptId");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Languages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Scripts.Script", b =>
                {
                    b.Property<int>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScriptId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("ScriptId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Scripts", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Worlds.World", b =>
                {
                    b.Property<int>("WorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorldId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("WorldId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Worlds", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.HistoryRecord", b =>
                {
                    b.Property<int>("HistoryRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryRecordId"));

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("HistoryRecordId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("UserId");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "ResourceKind", "ResourceId");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Castes.Caste", b =>
                {
                    b.HasOne("SkillCraft.Api.Core.Worlds.World", "World")
                        .WithMany("Castes")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Customizations.Customization", b =>
                {
                    b.HasOne("SkillCraft.Api.Core.Worlds.World", "World")
                        .WithMany("Customizations")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Languages.Language", b =>
                {
                    b.HasOne("SkillCraft.Api.Core.Scripts.Script", "Script")
                        .WithMany("Languages")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillCraft.Api.Core.Worlds.World", "World")
                        .WithMany("Languages")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Script");

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Scripts.Script", b =>
                {
                    b.HasOne("SkillCraft.Api.Core.Worlds.World", "World")
                        .WithMany("Scripts")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Scripts.Script", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Worlds.World", b =>
                {
                    b.Navigation("Castes");

                    b.Navigation("Customizations");

                    b.Navigation("Languages");

                    b.Navigation("Scripts");
                });
#pragma warning restore 612, 618
        }
    }
}
