// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillCraft.Api.Infrastructure;

#nullable disable

namespace SkillCraft.Api.PostgreSQL.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260810214646_CreateCharacterTables")]
    partial class CreateCharacterTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CasteEntity", b =>
                {
                    b.Property<int>("CasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CasteId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureContent")
                        .HasColumnType("text");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Skill")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("WealthRoll")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("CasteId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "FeatureName");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Skill");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Castes", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterCustomizationEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomizationId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "CustomizationId");

                    b.HasIndex("CustomizationId");

                    b.ToTable("CharacterCustomizations", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterId"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Alignment")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Attributes")
                        .HasColumnType("text");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<int>("CasteId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DominantHand")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("EducationId")
                        .HasColumnType("integer");

                    b.Property<string>("Eyes")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Flaws")
                        .HasColumnType("text");

                    b.Property<string>("Hair")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Ideals")
                        .HasColumnType("text");

                    b.Property<int>("LineageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("Skin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Traits")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId");

                    b.HasIndex("CasteId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("EducationId");

                    b.HasIndex("LineageId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "CasteId");

                    b.HasIndex("WorldId", "EducationId");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "LineageId");

                    b.HasIndex("WorldId", "Name");

                    b.ToTable("Characters", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterLanguageEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Target")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CharacterLanguages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterTalentEntity", b =>
                {
                    b.Property<int>("CharacterTalentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterTalentId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discounts")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Qualifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TalentId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterTalentId");

                    b.HasIndex("TalentId");

                    b.HasIndex("CharacterId", "Id")
                        .IsUnique();

                    b.ToTable("CharacterTalents", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CustomizationEntity", b =>
                {
                    b.Property<int>("CustomizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomizationId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomizationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Kind");

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Customizations", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.EducationEntity", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EducationId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureContent")
                        .HasColumnType("text");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Skill")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("WealthMultiplier")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("EducationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "FeatureName");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Skill");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Educations", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ItemEntity", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Category");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Price");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "Weight");

                    b.ToTable("Items", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LanguageEntity", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ScriptId")
                        .HasColumnType("integer");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypicalSpeakers")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguageId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("ScriptId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "ScriptId");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Languages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LineageEntity", b =>
                {
                    b.Property<int>("LineageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineageId"));

                    b.Property<int?>("Adult")
                        .HasColumnType("integer");

                    b.Property<int?>("Burrow")
                        .HasColumnType("integer");

                    b.Property<int?>("Climb")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomNames")
                        .HasColumnType("text");

                    b.Property<int>("ExtraLanguages")
                        .HasColumnType("integer");

                    b.Property<string>("FamilyNames")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("FemaleNames")
                        .HasColumnType("text");

                    b.Property<int?>("Fly")
                        .HasColumnType("integer");

                    b.Property<string>("HeightRoll")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Hover")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguagesContent")
                        .HasColumnType("text");

                    b.Property<string>("MaleNames")
                        .HasColumnType("text");

                    b.Property<string>("Malnutrition")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("Mature")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NamesContent")
                        .HasColumnType("text");

                    b.Property<string>("NormalWeight")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Obese")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Overweight")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("SizeCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Skinny")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Swim")
                        .HasColumnType("integer");

                    b.Property<int?>("Teenager")
                        .HasColumnType("integer");

                    b.Property<string>("UnisexNames")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Venerable")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("Walk")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("LineageId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("ParentId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "ParentId");

                    b.HasIndex("WorldId", "SizeCategory");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Lineages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LineageLanguageEntity", b =>
                {
                    b.Property<int>("LineageId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.HasKey("LineageId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LineageLanguages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", b =>
                {
                    b.Property<int>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScriptId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("ScriptId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Scripts", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.SpellEntity", b =>
                {
                    b.Property<int>("SpellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpellId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("SpellId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "Tier");

                    b.ToTable("Spells", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.TalentEntity", b =>
                {
                    b.Property<int>("TalentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TalentId"));

                    b.Property<bool>("AllowMultiplePurchases")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RequiredTalentId")
                        .HasColumnType("integer");

                    b.Property<string>("Skill")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("TalentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("RequiredTalentId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "AllowMultiplePurchases");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "RequiredTalentId");

                    b.HasIndex("WorldId", "Skill");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "Tier");

                    b.ToTable("Talents", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Property<int>("WorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorldId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("WorldId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Worlds", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CasteEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Castes")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterCustomizationEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.CharacterEntity", "Character")
                        .WithMany("Customizations")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.CustomizationEntity", "Customization")
                        .WithMany("Characters")
                        .HasForeignKey("CustomizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Customization");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.CasteEntity", "Caste")
                        .WithMany("Characters")
                        .HasForeignKey("CasteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.EducationEntity", "Education")
                        .WithMany("Characters")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.LineageEntity", "Lineage")
                        .WithMany("Characters")
                        .HasForeignKey("LineageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Characters")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caste");

                    b.Navigation("Education");

                    b.Navigation("Lineage");

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterLanguageEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.CharacterEntity", "Character")
                        .WithMany("Languages")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.LanguageEntity", "Language")
                        .WithMany("Characters")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterTalentEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.CharacterEntity", "Character")
                        .WithMany("Talents")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.TalentEntity", "Talent")
                        .WithMany("Characters")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CustomizationEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Customizations")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.EducationEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Educations")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ItemEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Items")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LanguageEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", "Script")
                        .WithMany("Languages")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Languages")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Script");

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LineageEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.LineageEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Lineages")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LineageLanguageEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.LanguageEntity", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.LineageEntity", null)
                        .WithMany()
                        .HasForeignKey("LineageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Scripts")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.SpellEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Spells")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.TalentEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.TalentEntity", "RequiredTalent")
                        .WithMany("RequiringTalents")
                        .HasForeignKey("RequiredTalentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Talents")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequiredTalent");

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CasteEntity", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.Navigation("Customizations");

                    b.Navigation("Languages");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CustomizationEntity", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.EducationEntity", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LanguageEntity", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.LineageEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.TalentEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("RequiringTalents");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Navigation("Castes");

                    b.Navigation("Characters");

                    b.Navigation("Customizations");

                    b.Navigation("Educations");

                    b.Navigation("Items");

                    b.Navigation("Languages");

                    b.Navigation("Lineages");

                    b.Navigation("Scripts");

                    b.Navigation("Spells");

                    b.Navigation("Talents");
                });
#pragma warning restore 612, 618
        }
    }
}
