// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillCraft.Api.Infrastructure;

#nullable disable

namespace SkillCraft.Api.PostgreSQL.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260802042601_ScriptEventSourcing")]
    partial class ScriptEventSourcing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillCraft.Api.Core.Castes.Caste", b =>
                {
                    b.Property<int>("CasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CasteId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureContent")
                        .HasColumnType("text");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Skill")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("WealthRoll")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("WorldEntityWorldId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("CasteId");

                    b.HasIndex("WorldEntityWorldId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "FeatureName");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Skill");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Castes", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Educations.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EducationId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureContent")
                        .HasColumnType("text");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Skill")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("WealthMultiplier")
                        .HasColumnType("integer");

                    b.Property<int?>("WorldEntityWorldId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("EducationId");

                    b.HasIndex("WorldEntityWorldId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "FeatureName");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Skill");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Educations", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Items.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int?>("WorldEntityWorldId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("WorldEntityWorldId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Price");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.HasIndex("WorldId", "Weight");

                    b.ToTable("Items", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Languages.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ScriptId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypicalSpeakers")
                        .HasColumnType("text");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorldEntityWorldId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguageId");

                    b.HasIndex("ScriptId");

                    b.HasIndex("WorldEntityWorldId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "ScriptId");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Languages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Lineages.Lineage", b =>
                {
                    b.Property<int>("LineageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineageId"));

                    b.Property<int?>("Adult")
                        .HasColumnType("integer");

                    b.Property<int?>("Burrow")
                        .HasColumnType("integer");

                    b.Property<int?>("Climb")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomNames")
                        .HasColumnType("text");

                    b.Property<int>("ExtraLanguages")
                        .HasColumnType("integer");

                    b.Property<string>("FamilyNames")
                        .HasColumnType("text");

                    b.Property<string>("FemaleNames")
                        .HasColumnType("text");

                    b.Property<int?>("Fly")
                        .HasColumnType("integer");

                    b.Property<string>("HeightRoll")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Hover")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguagesContent")
                        .HasColumnType("text");

                    b.Property<string>("MaleNames")
                        .HasColumnType("text");

                    b.Property<string>("Malnutrition")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("Mature")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NamesContent")
                        .HasColumnType("text");

                    b.Property<string>("NormalWeight")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Obese")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Overweight")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("SizeCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Skinny")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Swim")
                        .HasColumnType("integer");

                    b.Property<int?>("Teenager")
                        .HasColumnType("integer");

                    b.Property<string>("UnisexNames")
                        .HasColumnType("text");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Venerable")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("Walk")
                        .HasColumnType("integer");

                    b.Property<int?>("WorldEntityWorldId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("LineageId");

                    b.HasIndex("ParentId");

                    b.HasIndex("WorldEntityWorldId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "ParentId");

                    b.HasIndex("WorldId", "SizeCategory");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Lineages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Lineages.LineageFeature", b =>
                {
                    b.Property<int>("LineageFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineageFeatureId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("LineageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LineageFeatureId");

                    b.HasIndex("LineageId", "CreatedBy");

                    b.HasIndex("LineageId", "CreatedOn");

                    b.HasIndex("LineageId", "Id")
                        .IsUnique();

                    b.HasIndex("LineageId", "Name");

                    b.HasIndex("LineageId", "UpdatedBy");

                    b.HasIndex("LineageId", "UpdatedOn");

                    b.ToTable("LineageFeatures", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Spells.Spell", b =>
                {
                    b.Property<int>("SpellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpellId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorldEntityWorldId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("SpellId");

                    b.HasIndex("WorldEntityWorldId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "Tier");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Spells", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Configurations.LineageLanguage", b =>
                {
                    b.Property<int>("LineageId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.HasKey("LineageId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LineageLanguages", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CustomizationEntity", b =>
                {
                    b.Property<int>("CustomizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomizationId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomizationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Kind");

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Customizations", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", b =>
                {
                    b.Property<int>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScriptId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("ScriptId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Summary");

                    b.ToTable("Scripts", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.TalentEntity", b =>
                {
                    b.Property<int>("TalentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TalentId"));

                    b.Property<bool>("AllowMultiplePurchases")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RequiredTalentId")
                        .HasColumnType("integer");

                    b.Property<string>("Skill")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("TalentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("RequiredTalentId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "AllowMultiplePurchases");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "RequiredTalentId");

                    b.HasIndex("WorldId", "Skill");

                    b.HasIndex("WorldId", "Summary");

                    b.HasIndex("WorldId", "Tier");

                    b.ToTable("Talents", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Property<int>("WorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorldId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("WorldId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Worlds", "Game");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.HistoryRecord", b =>
                {
                    b.Property<int>("HistoryRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryRecordId"));

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("HistoryRecordId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("UserId");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "ResourceKind", "ResourceId");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Castes.Caste", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", null)
                        .WithMany("Castes")
                        .HasForeignKey("WorldEntityWorldId");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Educations.Education", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", null)
                        .WithMany("Educations")
                        .HasForeignKey("WorldEntityWorldId");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Items.Item", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("WorldEntityWorldId");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Languages.Language", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", null)
                        .WithMany("Languages")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", null)
                        .WithMany("Languages")
                        .HasForeignKey("WorldEntityWorldId");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Lineages.Lineage", b =>
                {
                    b.HasOne("SkillCraft.Api.Core.Lineages.Lineage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", null)
                        .WithMany("Lineages")
                        .HasForeignKey("WorldEntityWorldId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Lineages.LineageFeature", b =>
                {
                    b.HasOne("SkillCraft.Api.Core.Lineages.Lineage", "Lineage")
                        .WithMany("Features")
                        .HasForeignKey("LineageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lineage");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Spells.Spell", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", null)
                        .WithMany("Spells")
                        .HasForeignKey("WorldEntityWorldId");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Configurations.LineageLanguage", b =>
                {
                    b.HasOne("SkillCraft.Api.Core.Languages.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillCraft.Api.Core.Lineages.Lineage", null)
                        .WithMany()
                        .HasForeignKey("LineageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.CustomizationEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Customizations")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Scripts")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.TalentEntity", b =>
                {
                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.TalentEntity", "RequiredTalent")
                        .WithMany("RequiringTalents")
                        .HasForeignKey("RequiredTalentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillCraft.Api.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Talents")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequiredTalent");

                    b.Navigation("World");
                });

            modelBuilder.Entity("SkillCraft.Api.Core.Lineages.Lineage", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Features");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.ScriptEntity", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.TalentEntity", b =>
                {
                    b.Navigation("RequiringTalents");
                });

            modelBuilder.Entity("SkillCraft.Api.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Navigation("Castes");

                    b.Navigation("Customizations");

                    b.Navigation("Educations");

                    b.Navigation("Items");

                    b.Navigation("Languages");

                    b.Navigation("Lineages");

                    b.Navigation("Scripts");

                    b.Navigation("Spells");

                    b.Navigation("Talents");
                });
#pragma warning restore 612, 618
        }
    }
}
